language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - env: SYMFONY_VERSION=dev-master

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=dev-master

cache:
  apt: true
  directories:
    - $COMPOSER_CACHE_DIR

before_script:
  - sudo apt-get install geoip-bin
  - sudo apt-get install geoip-database
  - sudo apt-get install libgeoip-dev
  - ls -l /usr/share/GeoIP
  - curl -o GeoLiteCity.dat.gz https://cloud.github.com/downloads/lunetics/TimezoneBundle/GeoLiteCity.dat.gz
  - gunzip GeoLiteCity.dat.gz
  - sudo mkdir -p /usr/share/GeoIP
  - sudo mv GeoLiteCity.dat /usr/share/GeoIP/GeoIPCity.dat
  - pecl install geoip
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --dev --no-update
  - composer install --dev --prefer-source

script: phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: mb@lunetics.com
